version: "3.9"

services:
  app:
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Europe/Istanbul
    networks:
      - proxy
      - app_net
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  proxy:
    external: true
  app_net:
    driver: bridge