version: "3.9"

services:
  app:
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Europe/Istanbul
    networks:
      - proxy
      - app_net

networks:
  proxy:
    external: true
  app_net:
    driver: bridge